# Generated by Django 4.0.5 on 2022-07-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Last login time')),
                ('pin', models.SlugField(blank=True, max_length=20)),
                ('wait', models.CharField(blank=True, max_length=10)),
                ('cur_bot', models.BigIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg', models.CharField(max_length=100, unique=True, verbose_name='Telegram token')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Telegram username')),
                ('name', models.CharField(max_length=100, verbose_name='Bot name')),
                ('type', models.IntegerField(default=1)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('lng', models.CharField(default='ru', max_length=3, verbose_name='Bot language')),
                ('admins', models.ManyToManyField(to='bots.botadmin')),
            ],
        ),
    ]
