# Generated by Django 4.0.5 on 2022-07-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='admins',
            field=models.ManyToManyField(related_name='bot', to='bots.botadmin'),
        ),
    ]
