# Generated by Django 4.0.5 on 2022-08-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_alter_bot_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='password',
            field=models.CharField(default='pass123', max_length=50),
        ),
    ]
