# Generated by Django 4.1 on 2022-08-12 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_alter_bot_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botadmin',
            name='wait',
        ),
    ]
