# Generated by Django 4.1 on 2022-08-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_remove_botadmin_wait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botadmin',
            name='pin',
            field=models.SlugField(blank=True),
        ),
    ]
