# Generated by Django 4.1 on 2022-08-12 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edubot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='last_name',
        ),
    ]
