# Generated by Django 4.0.5 on 2022-07-13 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0002_alter_bot_admins'),
        ('plans', '0002_alter_plan_name_alter_planitem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spisok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.BigIntegerField(max_length=12, unique=True, verbose_name='Telegram ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('bots', models.ManyToManyField(related_name='spisok', to='bots.bot')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('pin', models.IntegerField(blank=True, verbose_name='Пин-код')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupbot', to='bots.bot')),
                ('plans', models.ManyToManyField(related_name='groupplan', to='plans.plan')),
                ('users', models.ManyToManyField(related_name='groupuser', to='groups.spisok')),
            ],
        ),
    ]
