# Generated by Django 4.0.5 on 2022-07-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_spisok_options_alter_group_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='pin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пин-код'),
        ),
    ]
