# Generated by Django 4.1 on 2022-08-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_spisok_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='pin',
            field=models.CharField(default=12345678, max_length=8, unique=True, verbose_name='Пин-код'),
            preserve_default=False,
        ),
    ]
