# Generated by Django 4.1 on 2022-08-12 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_temp_alter_group_pin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
