# Generated by Django 4.0.5 on 2022-07-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0003_alter_plan_name_alter_planitem_link_and_more'),
        ('bots', '0002_alter_bot_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='KR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название КР')),
                ('kolzad', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во заданий')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kr', to='bots.bot')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kr', to='plans.planitem', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='Номер задания')),
                ('text', models.TextField(max_length=100, verbose_name='Текст задания')),
                ('img', models.ImageField(blank=True, upload_to='temp')),
                ('kr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='kr.kr')),
            ],
        ),
    ]
