# Generated by Django 4.0.5 on 2022-07-15 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_plan_name_alter_planitem_link_and_more'),
        ('kr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kr',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kr', to='plans.planitem'),
        ),
    ]
