# Generated by Django 4.0.5 on 2022-07-23 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_plan_name_alter_planitem_link_and_more'),
        ('kr', '0002_alter_kr_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kr',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kr', to='plans.planitem', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, upload_to='temp/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(max_length=100, verbose_name='Текст задачи'),
        ),
    ]
