# Generated by Django 4.0.5 on 2022-08-02 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_group_pin'),
        ('kr', '0003_alter_kr_item_alter_task_img_alter_task_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='KROut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Время раздачи')),
                ('deadline', models.DateTimeField(default=None, verbose_name='Дедлайн сдачи')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kr_out', to='groups.group')),
                ('kr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kr_out', to='kr.kr')),
            ],
        ),
        migrations.CreateModel(
            name='TaskOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Время раздачи')),
                ('krout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_out', to='kr.krout')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_out', to='kr.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_out', to='groups.spisok')),
            ],
        ),
    ]
