# Generated by Django 4.0.5 on 2022-08-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kr', '0006_alter_krout_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskout',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер задания'),
            preserve_default=False,
        ),
    ]
