# Generated by Django 4.0.5 on 2022-08-03 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kr', '0007_taskout_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='krout',
            options={'ordering': ['-time']},
        ),
    ]
