# Generated by Django 4.1 on 2022-08-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kr', '0008_alter_krout_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Текст задачи'),
        ),
    ]
