# Generated by Django 4.0.5 on 2022-07-10 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Item name')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='bots.bot')),
            ],
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Item name')),
                ('link', models.URLField(blank=True)),
                ('type', models.CharField(choices=[('t', 'Теоретический материал'), ('k', 'Контрольная работа'), ('p', 'Практическая работа')], max_length=1, verbose_name='Bot name')),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_item', to='plans.plan')),
            ],
        ),
    ]
