# Generated by Django 4.0.5 on 2022-07-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Item name'),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Item name'),
        ),
    ]
