# Generated by Django 4.0.5 on 2022-07-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_plan_name_alter_planitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название плана'),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='link',
            field=models.URLField(blank=True, verbose_name='Ссылка на материалы'),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название темы'),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='type',
            field=models.CharField(choices=[('t', 'Теоретический материал'), ('k', 'Контрольная работа'), ('p', 'Практическая работа')], max_length=1, verbose_name='Тип занятия'),
        ),
    ]
