# Generated by Django 4.1 on 2022-08-07 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kr', '0009_alter_task_text'),
        ('plans', '0005_alter_plan_name_alter_planitem_name'),
        ('bots', '0003_alter_bot_password'),
        ('groups', '0005_alter_group_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('k', 'Контрольная работа'), ('p', 'Практическая работа')], max_length=1)),
                ('time', models.DateTimeField(auto_now=True)),
                ('link', models.URLField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('not_passed', 'Работа не сдана'), ('passed', 'Работа сдана'), ('done', 'Работа зачтена'), ('rejected', 'Работа отклонена')], default='not_passed', max_length=10)),
                ('review', models.TextField(blank=True, max_length=1000)),
                ('mark', models.PositiveSmallIntegerField(blank=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='bots.bot')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='groups.group')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='plans.planitem')),
                ('krout', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='kr.krout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='groups.spisok')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
