# Generated by Django 4.1 on 2022-08-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('not_passed', 'Работа не сдана'), ('passed', 'Работа сдана'), ('done', 'Работа зачтена'), ('rejected', 'Работа отклонена')], default='not_passed', max_length=10),
        ),
    ]
