# Generated by Django 4.1 on 2022-08-10 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_alter_work_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='group',
        ),
    ]
