# Generated by Django 4.1 on 2022-08-10 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kr', '0009_alter_task_text'),
        ('works', '0003_remove_work_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='krout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='kr.krout'),
        ),
    ]
